#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def isValid(arr,brr,item):
    for i in arr:
        if item % i !=0:
            return False
    for j in brr:
        if j % item != 0:
            return False
    return True







def getTotalX(arr, brr):
    c=0
#it selects one no from the given range and using isValid function checks the 2 conditions
    for item in range(arr[-1],brr[0]+1):
        if isValid(arr,brr,item):
            c=c+1
    return c











if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)


    fptr.write(str(total) + '\n')

    fptr.close()
