#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthday function below.
def birthday(s, d, m):
    c=0
    for i in range(len(s)):
        sum1=0
        a=0
        while(a<m):
            sum1=sum1+ s[i+a]
            a=a+1
        if sum1==d:
            c=c+1
        if (i+a) == len(s):
            break
    return c






        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = list(map(int, input().rstrip().split()))

    dm = input().rstrip().split()

    d = int(dm[0])

    m = int(dm[1])

    result = birthday(s, d, m)

    fptr.write(str(result) + '\n')

    fptr.close()
