#!/bin/python3

import math
import os
import random
import re
import sys

def isleap1(year):
    if year % 400==0:
        return True
    elif year % 4 == 0 and year % 100 != 0:
        return True
    else :
        return False

def isleap2(year):
    if year % 4 == 0:
        return True
    else:
        return False











# Complete the dayOfProgrammer function below.
def dayOfProgrammer(year):
    if year== 1918:
        a=256-230
    elif year > 1918:
        if isleap1(year):
            a=256-244
        else:
            a=256-243
    elif year < 1918:
        if isleap2(year):
            a=256-244
        else:
            a=256-243
    year1=str(year)
    b=str(a)
    return b + ".09." + year1




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()

    





    


