#!/bin/python3

import math
import os
import random
import re
import sys



def diagonalDifference(arr):
    sum1=0
    sum2=0
    counter1=0
    counter2= len(arr)-1
    arr1=[]
    for i in range (0,n):
        for j in range (0,n):
            if (i==j):
                sum1=sum1+arr[i][j]

    for a in range (len(arr)):
        arr1.append(arr[counter1][counter2])
        counter1=counter1+1
        counter2=counter2-1

        sum2=sum(arr1)




    return(abs(sum1-sum2))


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()

    
