#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    cpy=ar
    list1=[]
    c=0
    for i in range(len(ar)):
        for j in range(len(cpy)):
            if i<j:
                z=ar[i]+cpy[j]
                list1.append(z)

    for b in range(len(list1)):
        if list1[b] % k == 0:
            c=c+1
    return c













if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
