#!/bin/python3

import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):

    a=p//2   #forward cont
    b= (n-p)//2  #backward count


    if p==1 or p== n:
        return 0

    else:
        if a < b:
            return a
        elif b < a and p%2 != 0 and b==0:
            return 1
        else:
            return b
            




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
