#!/bin/python3

import os
import sys

#
# Complete the getMoneySpent function below.
#
def getMoneySpent(keyboards, drives, b):
    
    keyboards.sort(reverse=True)
    drives.sort(reverse=True)
    n=len(keyboards)
    m=len(drives)
    res=[]
    if keyboards[-1]>= b or drives[-1]>=b:
        if keyboards[-1] + drives[-1] >= b:
            return -1
    

    for i in range(0,n):
        for j in range(0,m):
            cost = keyboards[i]+drives[j] 
            if cost <= b:
                res.append(cost)

    return max(res)
                
               
            



    









if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    bnm = input().split()

    b = int(bnm[0])

    n = int(bnm[1])

    m = int(bnm[2])

    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))

    #
    # The maximum amount of money she can spend on a keyboard and USB drive, or -1 if she can't purchase both items
    #

    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
