#!/bin/python3

import math
import os
import random
import re
import sys


# Complete the plusMinus function below.
def plusMinus(arr):
    
    
    pos=0
    nev=0
    ze=0
    for i in range(0,n):
        if (arr[i]>0):
            pos=pos+1
            #print(pos)
    for i in range(0,n):
        if (arr[i]<0):
            nev=nev+1
            #print(nev)
    for i in range(0,n):
        if (arr[i]==0):
            ze=ze+1
            #print(ze)
    dec_places = "%."+str(n)+"f"

    print(dec_places % (pos/n))
    print(dec_places % (nev/n))
    print(dec_places % (ze/n))

      

if __name__ == '__main__':
    n = int(input())



    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
