#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    pair=[]
    new_pair=[]
    set1=set(ar)
    list1=list(set1)
    
    while(len(list1)>0):
        c=0

        #print(list1)
        for i in range (0,len(ar)):
            if ar[i]==list1[-1]:
                c=c+1
        #print(c)
        list1.pop()
        #print(list1)
        pair.append(c)
        #print(pair)

    for j in range (0,len(pair)):
        if(pair[j]>1):
            a = pair[j]//2 
            new_pair.append(a)
    #print(new_pair)
    return(sum(new_pair))
            
            




         

    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
